# 公共配置参数
comm:
  loglevel: 0
  logpath: /home/admin/chogolisa

# mysql数据库
mysql:
  url_horde: chogolisa:1dbnImbzYShprC63@tcp(horde-real-mysql.ortiot.com:3306)/horde?charset=utf8&parseTime=True&loc=Local

# redis数据库
redis:
  address: horde-real-redis.ortiot.com
  passwprd: e48f37e8e4148ba0
  maxidle: 10
  maxac: 10
  db: 3

# api配置
api:
  key: chogolisa

# app 配置
app:
  port: 8080
  source: chogolisa
  secret: adsgsag2rEGljmeasdfas
  salt: dfasfhasfhuiahkgk
  simcode:
    url: simcode.dian.so
    port: 9001
    apikey: simcode
    source: simcode
    secret: adsgsag2rEGljmefWfP
    salt: dfasfhasfhuiahufd
  azeroth:
    url: http://azeroth-in.ortiot.com


device:
  cluster_id: 1

# 腾讯云cos
cos:
  url: https://cloud-fw-1255721034.cos.ap-shanghai.myqcloud.com
  cdn: https://fw.dian.so
  secretid: AKIDljlp1EJqUhwQ0dI62yuATmWLLMwalqaL
  secretkey: VfwJdFtGA9JUfq2dHvbetGykXKA3xtqo